# NOTE: update this with your service name
service: readme-grades-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-2
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

# Environmental variables below
environment:
  tableName: process.env.TableName

#iamRoleStatements - Access policies

iamRoleStatements:
  - Effect: Allow
    Action:
      - sts:AssumeRole
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:DescribeTable
    Resource:
      - "arn:aws:dynamodb:us-west-2:*:*"

functions:
  get:
    # API Gateway endpoint for get function.
    #path: grades/{id}
    # method: GET request
    handler: get.main # Function to be called
    events:
      - http:
          path: grades
          method: get
resources:
  - ${file(resources/api-gateway-errors.yml)}
